services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rj
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    # env_file:
    #   - .docker.env
    environment:
      DB_PRISMA_URL: "postgresql://test:example@db:5432/rj?schema=public"
      DB_URL_NON_POOLING: "postgresql://test:example@db:5432/rj?schema=public"

volumes:
  pgdata:
