services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rj
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: ghcr.io/marker-bit/rj:prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    # env_file:
    #   - .docker.env
    healthcheck:
      test: ["CMD", "wget", "-q", "http://0.0.0.0:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      DB_PRISMA_URL: "postgresql://test:example@db:5432/rj?schema=public"
      DB_URL_NON_POOLING: "postgresql://test:example@db:5432/rj?schema=public"

volumes:
  pgdata:
